In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [3]:
# Importing the dataset
df = pd.read_csv('pune.csv')
df

Date      Time  maxtempC  mintempC  totalSnow_cm  sunHour  uvIndex  \
0      1/1/2009   0:00:00        31        13             0     11.0        6   
1      1/1/2009   1:00:00        31        13             0     11.0        6   
2      1/1/2009   2:00:00        31        13             0     11.0        6   
3      1/1/2009   3:00:00        31        13             0     11.0        6   
4      1/1/2009   4:00:00        31        13             0     11.0        6   
...         ...       ...       ...       ...           ...      ...      ...   
96427  1/1/2020  19:00:00        29        18             0     11.0        6   
96428  1/1/2020  20:00:00        29        18             0     11.0        6   
96429  1/1/2020  21:00:00        29        18             0     11.0        6   
96430  1/1/2020  22:00:00        29        18             0     11.0        6   
96431  1/1/2020  23:00:00        29        18             0     11.0        6   

       uvIndex.1  moon_illumination  moonrise  ... WindGustKmph cloudcover  \
0              1                 31  10:17 AM  ...            7          0   
1              1                 31  10:17 AM  ...            9          0   
2              1                 31  10:17 AM  ...           10          0   
3              1                 31  10:17 AM  ...           12          0   
4              1                 31  10:17 AM  ...           11          1   
...          ...                ...       ...  ...          ...        ...   
96427          1                 37  11:34 AM  ...           20          3   
96428          1                 37  11:34 AM  ...           19          3   
96429          1                 37  11:34 AM  ...           18          2   
96430          1                 37  11:34 AM  ...           17          2   
96431          1                 37  11:34 AM  ...           16          2   

      humidity  precipMM  pressure  tempC  visibility  winddirDegree  \
0           50       0.0      1013     13          10             59   
1           47       0.0      1013     14          10             57   
2           44       0.0      1013     14          10             55   
3           41       0.0      1013     15          10             54   
4           38       0.0      1014     16          10             68   
...        ...       ...       ...    ...         ...            ...   
96427       49       0.0      1014     23          10            255   
96428       53       0.0      1014     22          10            258   
96429       57       0.0      1015     21          10            262   
96430       60       0.0      1015     20          10            264   
96431       62       0.0      1015     20          10            267   

       windspeedKmph  Rain  
0                  3     0  
1                  4     0  
2                  5     0  
3                  6     0  
4                  6     0  
...              ...   ...  
96427             12     0  
96428             11     0  
96429             10     0  
96430              9     0  
96431              9     0  

[96432 rows x 27 columns]

In [4]:
wt = wt = df[["Date","Time","maxtempC","mintempC","DewPointC","cloudcover","humidity","pressure","visibility","windspeedKmph","precipMM","Rain"]].copy()
wt

Date      Time  maxtempC  mintempC  DewPointC  cloudcover  \
0      1/1/2009   0:00:00        31        13          7           0   
1      1/1/2009   1:00:00        31        13          6           0   
2      1/1/2009   2:00:00        31        13          6           0   
3      1/1/2009   3:00:00        31        13          5           0   
4      1/1/2009   4:00:00        31        13          5           1   
...         ...       ...       ...       ...        ...         ...   
96427  1/1/2020  19:00:00        29        18         11           3   
96428  1/1/2020  20:00:00        29        18         12           3   
96429  1/1/2020  21:00:00        29        18         12           2   
96430  1/1/2020  22:00:00        29        18         12           2   
96431  1/1/2020  23:00:00        29        18         13           2   

       humidity  pressure  visibility  windspeedKmph  precipMM  Rain  
0            50      1013          10              3       0.0     0  
1            47      1013          10              4       0.0     0  
2            44      1013          10              5       0.0     0  
3            41      1013          10              6       0.0     0  
4            38      1014          10              6       0.0     0  
...         ...       ...         ...            ...       ...   ...  
96427        49      1014          10             12       0.0     0  
96428        53      1014          10             11       0.0     0  
96429        57      1015          10             10       0.0     0  
96430        60      1015          10              9       0.0     0  
96431        62      1015          10              9       0.0     0  

[96432 rows x 12 columns]

In [23]:
X = wt.iloc[:,[2,3,4,7,8,9,10,11]].values
y = wt.iloc[:,-1].values
print(X)
print(y)

[[31. 13.  7. ...  3.  0.  0.]
 [31. 13.  6. ...  4.  0.  0.]
 [31. 13.  6. ...  5.  0.  0.]
 ...
 [29. 18. 12. ... 10.  0.  0.]
 [29. 18. 12. ...  9.  0.  0.]
 [29. 18. 13. ...  9.  0.  0.]]
[0 0 0 ... 0 0 0]


In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[22.  21.  22.  ...  5.   0.   0. ]
 [29.  16.  13.  ...  9.   0.   0. ]
 [28.  14.   3.  ...  6.   0.   0. ]
 ...
 [29.  16.  10.  ... 10.   0.   0. ]
 [29.  14.  10.  ...  6.   0.   0. ]
 [28.  21.  17.  ...  9.   0.1  1. ]]
[[28.  15.  13.  ...  6.   0.   0. ]
 [31.  20.  16.  ...  6.   0.   0. ]
 [28.  22.  22.  ...  4.   0.7  1. ]
 ...
 [30.  13.   2.  ...  4.   0.   0. ]
 [40.  22.   9.  ... 11.   0.   0. ]
 [31.  22.  21.  ... 14.   0.   0. ]]
[0 0 0 ... 0 0 1]
[0 0 1 ... 0 0 0]


In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.fit_transform(X_test)

print(X_train)
print(X_test)

[[-2.04169339  0.25043176  1.12520987 ... -0.88327694 -0.1783512
  -0.36731646]
 [-0.44461913 -1.34826072 -0.29634097 ... -0.13333275 -0.1783512
  -0.36731646]
 [-0.6727726  -1.98773771 -1.87584189 ... -0.6957909  -0.1783512
  -0.36731646]
 ...
 [-0.44461913 -1.34826072 -0.77019124 ...  0.0541533  -0.1783512
  -0.36731646]
 [-0.44461913 -1.98773771 -0.77019124 ... -0.6957909  -0.1783512
  -0.36731646]
 [-0.6727726   0.25043176  0.33545941 ... -0.13333275  0.07587782
   2.7224481 ]]
[[-0.67166653 -1.64330152 -0.29485417 ... -0.68372582 -0.17182458
  -0.36330486]
 [ 0.01471966 -0.05557186  0.18227996 ... -0.68372582 -0.17182458
  -0.36330486]
 [-0.67166653  0.57952001  1.13654821 ... -1.05526752  1.56065014
   2.75250928]
 ...
 [-0.21407573 -2.27839338 -2.04434596 ... -1.05526752 -0.17182458
  -0.36330486]
 [ 2.07387824  0.57952001 -0.931033   ...  0.24512845 -0.17182458
  -0.36330486]
 [ 0.01471966  0.57952001  0.97750351 ...  0.802441   -0.17182458
  -0.36330486]]


In [27]:
from sklearn.linear_model import LogisticRegression
Logreg = LogisticRegression()
Logreg.fit(X_train, y_train)

LogisticRegression()

In [28]:
y_pred = Logreg.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [29]:
combined = np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)

In [30]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[21297     0]
 [    0  2811]]


In [31]:
accuracy_score(y_test, y_pred)

1.0