In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [22]:
# Importing the dataset
df = pd.read_csv('pune2.csv')
df

Date  maxtempC  mintempC  totalSnow_cm  sunHour  uvIndex  \
0       1/1/2009        31        13             0     11.0        6   
1       1/2/2009        30        15             0     11.0        6   
2       1/3/2009        30        15             0     11.0        6   
3       1/4/2009        31        14             0     11.0        6   
4       1/5/2009        30        15             0     11.0        6   
...          ...       ...       ...           ...      ...      ...   
4014  12/29/2019        28        17             0      7.0        6   
4015  12/30/2019        29        18             0     11.0        6   
4016  12/31/2019        29        18             0     11.0        6   
4017    1/1/2020        29        18             0     11.0        6   
4018         NaN         0         0             0      0.0        0   

      uvIndex.1  moon_illumination  moonrise   moonset  ... cloudcover  \
0      3.791667                 31  12:00 AM  12:00 AM  ...   0.625000   
1      3.750000                 38  12:00 AM  12:00 AM  ...   3.833333   
2      3.750000                 45  12:00 AM  12:00 AM  ...   4.041667   
3      3.875000                 52  12:00 AM  12:00 AM  ...   5.291667   
4      3.833333                 60  12:00 AM  12:00 AM  ...   8.416667   
...         ...                ...       ...       ...  ...        ...   
4014   3.375000                 15  12:00 AM  12:00 AM  ...  47.833333   
4015   3.750000                 22  12:00 AM  12:00 AM  ...   6.541667   
4016   3.750000                 26  12:00 AM  12:00 AM  ...   2.125000   
4017   3.708333                 37  12:00 AM  12:00 AM  ...   3.500000   
4018   0.000000                  0  12:00 AM  12:00 AM  ...   0.000000   

       humidity  precipMM     pressure      tempC  visibility  winddirDegree  \
0     37.125000  0.000000  1012.875000  20.500000   10.000000      77.000000   
1     45.000000  0.000000  1013.625000  20.958333   10.000000     122.666667   
2     48.625000  0.000000  1014.833333  20.791667   10.000000     137.541667   
3     51.875000  0.000000  1013.625000  21.208333   10.000000     159.708333   
4     51.208333  0.000000  1011.750000  21.750000   10.000000     223.041667   
...         ...       ...          ...        ...         ...            ...   
4014  65.291667  0.016667  1012.958333  22.333333    9.916667     160.833333   
4015  68.250000  0.000000  1012.083333  22.958333   10.000000     200.625000   
4016  57.583333  0.000000  1013.166667  22.125000   10.000000     277.291667   
4017  47.208333  0.000000  1013.583333  22.250000   10.000000     218.458333   
4018   0.000000  0.000000     0.000000   0.000000    0.000000       0.000000   

      windspeedKmph  maxtempC.1  Rain  
0          4.500000          31     0  
1          5.458333          30     0  
2          3.750000          30     0  
3          2.583333          31     0  
4          4.791667          30     0  
...             ...         ...   ...  
4014       7.125000          28     1  
4015       8.166667          29     0  
4016       7.791667          29     0  
4017       8.791667          29     0  
4018       0.000000           0     0  

[4019 rows x 27 columns]

In [24]:
wt  = df[["Date","maxtempC","mintempC","DewPointC","cloudcover","humidity","pressure","visibility","windspeedKmph","precipMM","Rain"]].copy()
wt

Date  maxtempC  mintempC  DewPointC  cloudcover   humidity  \
0       1/1/2009        31        13   7.166667    0.625000  37.125000   
1       1/2/2009        30        15   9.250000    3.833333  45.000000   
2       1/3/2009        30        15  10.208333    4.041667  48.625000   
3       1/4/2009        31        14  11.250000    5.291667  51.875000   
4       1/5/2009        30        15  11.208333    8.416667  51.208333   
...          ...       ...       ...        ...         ...        ...   
4014  12/29/2019        28        17  15.125000   47.833333  65.291667   
4015  12/30/2019        29        18  15.833333    6.541667  68.250000   
4016  12/31/2019        29        18  11.666667    2.125000  57.583333   
4017    1/1/2020        29        18   9.958333    3.500000  47.208333   
4018         NaN         0         0   0.000000    0.000000   0.000000   

         pressure  visibility  windspeedKmph  precipMM  Rain  
0     1012.875000   10.000000       4.500000  0.000000     0  
1     1013.625000   10.000000       5.458333  0.000000     0  
2     1014.833333   10.000000       3.750000  0.000000     0  
3     1013.625000   10.000000       2.583333  0.000000     0  
4     1011.750000   10.000000       4.791667  0.000000     0  
...           ...         ...            ...       ...   ...  
4014  1012.958333    9.916667       7.125000  0.016667     1  
4015  1012.083333   10.000000       8.166667  0.000000     0  
4016  1013.166667   10.000000       7.791667  0.000000     0  
4017  1013.583333   10.000000       8.791667  0.000000     0  
4018     0.000000    0.000000       0.000000  0.000000     0  

[4019 rows x 11 columns]

In [28]:
X = wt.iloc[:,[1,2,3,4,7,8,9]].values
y = wt.iloc[:,-1].values
print(X)
print(y)

[[31.   13.    7.17 ... 10.    4.5   0.  ]
 [30.   15.    9.25 ... 10.    5.46  0.  ]
 [30.   15.   10.21 ... 10.    3.75  0.  ]
 ...
 [29.   18.   11.67 ... 10.    7.79  0.  ]
 [29.   18.    9.96 ... 10.    8.79  0.  ]
 [ 0.    0.    0.   ...  0.    0.    0.  ]]
[0 0 0 ... 0 0 0]


In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[27.   18.   18.67 ...  6.75  4.42  0.  ]
 [31.   20.   15.83 ... 10.    4.92  0.  ]
 [32.   16.    7.25 ... 10.    3.12  0.  ]
 ...
 [24.   21.   20.42 ...  9.62 16.88  0.27]
 [35.   22.   13.92 ... 10.    6.04  0.  ]
 [25.   22.   21.04 ...  8.96 12.92  0.23]]
[[2.80e+01 2.10e+01 2.07e+01 ... 9.62e+00 1.36e+01 1.13e-01]
 [3.50e+01 2.40e+01 2.02e+01 ... 9.46e+00 1.06e+01 2.54e-01]
 [3.40e+01 2.10e+01 1.57e+01 ... 9.92e+00 6.21e+00 8.33e-03]
 ...
 [2.90e+01 1.70e+01 1.15e+01 ... 1.00e+01 1.05e+01 0.00e+00]
 [3.70e+01 2.20e+01 8.38e+00 ... 1.00e+01 6.38e+00 0.00e+00]
 [2.80e+01 2.10e+01 2.10e+01 ... 7.50e+00 1.06e+01 2.92e-02]]
[0 0 0 ... 1 0 1]
[1 1 1 1 1 1 1 1 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0
 0 0 1 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 1 1 0 0 0 0
 1 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 0 0 1
 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 1 1 1 0 0 1 1 0 0 1 0 1 1 0

In [30]:
 from sklearn.preprocessing import StandardScaler
 sc = StandardScaler()
 X_train= sc.fit_transform(X_train)
 X_test= sc.fit_transform(X_test)

 print(X_train)
 print(X_test)

[[-0.9  -0.69  0.65 ... -2.11 -1.19 -0.32]
 [ 0.   -0.06  0.17 ...  0.39 -1.07 -0.32]
 [ 0.23 -1.32 -1.26 ...  0.39 -1.48 -0.32]
 ...
 [-1.59  0.26  0.94 ...  0.1   1.61  0.93]
 [ 0.91  0.58 -0.15 ...  0.39 -0.82 -0.32]
 [-1.36  0.58  1.04 ... -0.41  0.72  0.78]]
[[-0.62  0.22  0.93 ...  0.14  0.88  0.11]
 [ 0.97  1.18  0.84 ...  0.01  0.2   0.56]
 [ 0.74  0.22  0.09 ...  0.36 -0.79 -0.23]
 ...
 [-0.4  -1.06 -0.6  ...  0.42  0.17 -0.25]
 [ 1.42  0.54 -1.12 ...  0.42 -0.75 -0.25]
 [-0.62  0.22  0.98 ... -1.46  0.21 -0.16]]


In [31]:
from sklearn.linear_model import LogisticRegression
Logreg = LogisticRegression()
Logreg.fit(X_train, y_train)

LogisticRegression()

In [32]:
y_pred = Logreg.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [0 1]
 ...
 [0 0]
 [0 0]
 [1 1]]


In [33]:
combined = np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)
combined

array([[1, 1],
       [1, 1],
       [0, 1],
       ...,
       [0, 0],
       [0, 0],
       [1, 1]])

In [34]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[432  43]
 [ 16 313]]


In [35]:
accuracy_score(y_test, y_pred)

0.9266169154228856

In [36]:
p = Logreg.predict_proba(X_test)
p

array([[4.00e-03, 9.96e-01],
       [2.56e-05, 1.00e+00],
       [6.85e-01, 3.15e-01],
       ...,
       [9.73e-01, 2.67e-02],
       [9.53e-01, 4.73e-02],
       [7.34e-02, 9.27e-01]])